/*
 * FreeDockPanel.java
 *
 * Created on September 26, 2000, 1:11 PM
 */

package com.SoftWoehr.JaXWT;

/**
 *
 * @author  jax
 * @version
 */
public class FreeDockPanel extends javax.swing.JPanel {

  /** Creates new form FreeDockPanel */
  public FreeDockPanel() {
    initComponents ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    setLayout (new java.awt.BorderLayout ());

  }//GEN-END:initComponents

  /**
   * @param fp
   */
  protected void hookBeforeDocking(FreePanel fp) {

  }

  /**
   * @param fp
   */
  protected void hookAfterDocking(FreePanel fp) {

  }

  /**
   * @param fp
   */
  protected void hookBeforeUnDocking(FreePanel fp) {

  }

  /**
   * @param fp
   */
  protected void hookAfterUnDocking(FreePanel fp) {

  }

  /**
   * @param fp
   */
  public void dock(FreePanel fp) {
    hookBeforeDocking(fp);
    add(fp);
    hookAfterDocking(fp);
  }

  /**
   * @param fp
   */
  public void undock(FreePanel fp) {
    hookBeforeUnDocking(fp);
    remove(fp);
    hookAfterUnDocking(fp);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}