/*
 * FreePanel.java
 *
 * Created on September 26, 2000, 1:15 PM
 */

package com.SoftWoehr.JaXWT;

/**
 *
 * @author  jax
 * @version
 */
public class FreePanel extends javax.swing.JPanel {

  /** Creates new form FreePanel */
  public FreePanel() {
    initComponents ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    setLayout (new java.awt.BorderLayout ());

  }//GEN-END:initComponents

  /** Undock from current (or null) and dock into new (or null)
   * @param fdp
   */
  public void dock (FreeDockPanel fdp) {
    if (null != getParent()) {
      ((FreeDockPanel)getParent()).undock(this);
    }
    if (null != fdp) {
      fdp.dock(this);
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}